apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redirect-check-frontend
spec:
  replicas: 1
  template:
    metadata:
      name: redirect-check-frontend
      labels:
        app: redirect-check-frontend
        role: frontend
        env: production
    spec:
      containers:
      - name: redirect-check-frontend
#Image tag is changed by Jenkins during build
        image: <IMAGE_TAG_DO_NOT_EDIT>
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
#        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 80
        ports:
        - name: frontend
          containerPort: 80
