apiVersion: v1
kind: Service
metadata:
  name: redirect-check-frontend-service
spec:
#  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: redirect-check-frontend
    role: frontend
